# Site settings
title: Artists Theme
description: Thinker // Designer // YouTuber
email: artist@email



# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed